# Read Database

In [39]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('bmarket.db') 

sql_query = "SELECT * FROM bank_marketing"

df = pd.read_sql(sql_query, conn)

conn.close()

df.head()

,Client ID,Age,Occupation,Marital Status,Education Level,Credit Default,Housing Loan,Personal Loan,Contact Method,Campaign Calls,Previous Contact Days,Subscription Status
0,32885,57 years,technician,married,high.school,no,no,yes,Cell,1,999,no
1,3170,55 years,unknown,married,unknown,unknown,yes,no,telephone,2,999,no
2,32207,33 years,blue-collar,married,basic.9y,no,no,no,cellular,1,999,no
3,9404,36 years,admin.,married,high.school,no,no,no,Telephone,4,999,no
4,14021,27 years,housemaid,married,high.school,no,None,no,Cell,2,999,no

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Client ID              41188 non-null  int64
 1   Age                    41188 non-null  object
 2   Occupation             41188 non-null  object
 3   Marital Status         41188 non-null  object
 4   Education Level        41188 non-null  object
 5   Credit Default         41188 non-null  object
 6   Housing Loan           16399 non-null  object
 7   Personal Loan          37042 non-null  object
 8   Contact Method         41188 non-null  object
 9   Campaign Calls         41188 non-null  int64
 10  Previous Contact Days  41188 non-null  int64
 11  Subscription Status    41188 non-null  object
dtypes: int64(3), object(9)
memory usage: 3.8+ MB

# Data Cleaning

In [41]:
df_drop_dups = df.drop_duplicates()
df_drop_dups

,Client ID,Age,Occupation,Marital Status,Education Level,Credit Default,Housing Loan,Personal Loan,Contact Method,Campaign Calls,Previous Contact Days,Subscription Status
0,32885,57 years,technician,married,high.school,no,no,yes,Cell,1,999,no
1,3170,55 years,unknown,married,unknown,unknown,yes,no,telephone,2,999,no
2,32207,33 years,blue-collar,married,basic.9y,no,no,no,cellular,1,999,no
3,9404,36 years,admin.,married,high.school,no,no,no,Telephone,4,999,no
4,14021,27 years,housemaid,married,high.school,no,None,no,Cell,2,999,no
...,...,...,...,...,...,...,...,...,...,...,...,...
41183,6266,58 years,retired,married,professional.course,unknown,no,no,Telephone,2,999,no
41184,11285,37 years,management,married,university.degree,no,no,no,telephone,1,999,no
41185,38159,35 years,admin.,married,high.school,no,None,no,cellular,1,4,yes
41186,861,40 years,management,married,university.degree,no,None,no,telephone,2,999,no
41187,15796,29 years,admin.,single,university.degree,no,yes,no,Cell,2,999,no

Explain that there is no duplicates

In [42]:
print(list(df_drop_dups.columns))

for tag in list(df_drop_dups.columns):
    print(f"\n {tag}: {df_drop_dups[tag].unique()}")

['Client ID', 'Age', 'Occupation', 'Marital Status', 'Education Level', 'Credit Default', 'Housing Loan', 'Personal Loan', 'Contact Method', 'Campaign Calls', 'Previous Contact Days', 'Subscription Status']

 Client ID: [32885  3170 32207 ... 38159   861 15796]

 Age: ['57 years' '55 years' '33 years' '36 years' '27 years' '58 years'
 '48 years' '150 years' '24 years' '34 years' '42 years' '43 years'
 '26 years' '37 years' '46 years' '59 years' '49 years' '30 years'
 '51 years' '45 years' '31 years' '41 years' '38 years' '47 years'
 '69 years' '50 years' '25 years' '39 years' '44 years' '52 years'
 '35 years' '77 years' '40 years' '56 years' '53 years' '60 years'
 '29 years' '28 years' '54 years' '32 years' '81 years' '63 years'
 '21 years' '22 years' '74 years' '80 years' '62 years' '68 years'
 '86 years' '23 years' '71 years' '67 years' '65 years' '20 years'
 '19 years' '66 years' '75 years' '18 years' '72 years' '70 years'
 '82 years' '85 years' '61 years' '88 years' '83 years' '78 years'
 '64 years' '17 years' '76 years' '73 years' '79 years' '89 years'
 '84 years' '91 years' '98 years' '92 years' '95 years']

 Occupation: ['technician' 'unknown' 'blue-collar' 'admin.' 'housemaid' 'retired'
 'services' 'entrepreneur' 'unemployed' 'management' 'self-employed'
 'student']

 Marital Status: ['married' 'divorced' 'single' 'unknown']

 Education Level: ['high.school' 'unknown' 'basic.9y' 'professional.course'
 'university.degree' 'basic.4y' 'basic.6y' 'illiterate']

 Credit Default: ['no' 'unknown' 'yes']

 Housing Loan: ['no' 'yes' None 'unknown']

 Personal Loan: ['yes' 'no' None 'unknown']

 Contact Method: ['Cell' 'telephone' 'cellular' 'Telephone']

 Campaign Calls: [  1   2   4   7   3 -11  15  -3  12   9  -1   5  -9  -5   6  13  -2  14
 -12  42   8  11  -4  17  18  10  -8  -6  28  33  -7  16  24  20  21  22
  23 -14  19 -29  26 -18 -13  25 -16 -28  32 -22  27  30  29  31 -10 -20
 -35  56 -17 -15 -32  40 -21 -23  43  35 -19  34 -41  39  37 -25]

 Previous Contact Days: [999   3  10   6  13   4  12   5   9  15  14   7  16   1   0   2  11   8
  17  18  21  19  26  22  27  20  25]

 Subscription Status: ['no' 'yes']

This is to check the type of tags within the information

In [43]:
df_drop_dups["Age"] = df_drop_dups["Age"].apply(lambda x: int(x.split()[0]))
df_drop_dups

,Client ID,Age,Occupation,Marital Status,Education Level,Credit Default,Housing Loan,Personal Loan,Contact Method,Campaign Calls,Previous Contact Days,Subscription Status
0,32885,57,technician,married,high.school,no,no,yes,Cell,1,999,no
1,3170,55,unknown,married,unknown,unknown,yes,no,telephone,2,999,no
2,32207,33,blue-collar,married,basic.9y,no,no,no,cellular,1,999,no
3,9404,36,admin.,married,high.school,no,no,no,Telephone,4,999,no
4,14021,27,housemaid,married,high.school,no,None,no,Cell,2,999,no
...,...,...,...,...,...,...,...,...,...,...,...,...
41183,6266,58,retired,married,professional.course,unknown,no,no,Telephone,2,999,no
41184,11285,37,management,married,university.degree,no,no,no,telephone,1,999,no
41185,38159,35,admin.,married,high.school,no,None,no,cellular,1,4,yes
41186,861,40,management,married,university.degree,no,None,no,telephone,2,999,no
41187,15796,29,admin.,single,university.degree,no,yes,no,Cell,2,999,no

In [47]:
df_drop_dups['Contact Method'] = df_drop_dups['Contact Method'].str.lower().str.strip()

df_drop_dups['Contact Method'] = df_drop_dups['Contact Method'].replace({
    'cell': 'cellular', 'Telephone': 'telephone'})

df_drop_dups['Housing Loan'] = df_drop_dups['Housing Loan'].replace({ None: "unknown" })

df_drop_dups['Personal Loan'] = df_drop_dups['Personal Loan'].replace({ None: "unknown" })

In [49]:
df_drop_dups['Contact Method'].value_counts()

Contact Method
cellular     26144
telephone    15044
Name: count, dtype: int64

In [48]:
df_drop_dups['Personal Loan'].value_counts()

Personal Loan
no         30532
yes         5633
unknown     5023
Name: count, dtype: int64

In [50]:
df_drop_dups["Housing Loan"].value_counts()

Housing Loan
unknown    25182
yes         8595
no          7411
Name: count, dtype: int64